openapi: 3.0.1
info:
  title: Parktiv
  description: Parktiv Backend Service PBS
  version: "0.3"
servers:
- url: /parktiv
tags:
- name: park
paths:
  /parks:
    get:
      tags:
      - park
      summary: List of parks containing a QR-Code
      description: |
        Returns a list of all parks which are currently support by Parktiv and having a QR-Code
      operationId: list_park
      parameters:
      - name: Accept_Language
        in: header
        description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParksResponse'
      x-openapi-router-controller: parktiv_server.controllers.park_controller
  /animals:
    get:
      tags:
      - park
      summary: List of all available animals with exercises
      description: List of all available animals with exercises
      operationId: list_animal
      parameters:
      - name: Accept_Language
        in: header
        description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalResponse'
      x-openapi-router-controller: parktiv_server.controllers.park_controller
  /animals/memory/random:
    get:
      tags:
      - park
      summary: Retrieve a random list of animal ids
      description: "Returns a random list of animal identifiers. Each identifier is\
        \ returned twice to support the game memory \n"
      operationId: animals_memory_random_get
      parameters:
      - name: size
        in: query
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 1
          type: integer
          default: 4
      - name: Accept_Language
        in: header
        description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryResponse'
        "409":
          description: Invalid size value
          content: {}
      x-openapi-router-controller: parktiv_server.controllers.park_controller
  /roles:
    get:
      tags:
      - park
      summary: List of roles which can be chosen to complete different exersices
      description: List of roles which can be chosen to complete different exersices
      operationId: roles_get
      parameters:
      - name: Accept_Language
        in: header
        description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleResponse'
      x-openapi-router-controller: parktiv_server.controllers.park_controller
  /animals/{identifier}/task/{roleId}:
    get:
      tags:
      - park
      summary: Get a specific animal including the task
      description: Get a specific animal including the the related task for the role.
      operationId: get_animal
      parameters:
      - name: identifier
        in: path
        description: Animal identifier
        required: true
        style: simple
        explode: false
        schema:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
      - name: roleId
        in: path
        description: Role identifier
        required: true
        style: simple
        explode: false
        schema:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
      - name: Accept_Language
        in: header
        description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalWithTask'
        "404":
          description: Invalid identifier supplied
          content: {}
      x-openapi-router-controller: parktiv_server.controllers.park_controller
components:
  schemas:
    Image:
      required:
      - url
      type: object
      properties:
        url:
          minLength: 1
          type: string
          description: Server path to an image
        copyright:
          minLength: 1
          type: string
          description: Copyright information for the image which must be set when
            displaying
      example:
        copyright: copyright
        url: url
    MemoryResponse:
      required:
      - ids
      type: object
      properties:
        ids:
          minItems: 1
          type: array
          items:
            minLength: 1
            pattern: "^[a-zA-Z0-9_-]{1,30}$"
            type: string
      example:
        ids:
        - ids
        - ids
    AnimalResponse:
      type: object
      properties:
        animals:
          minItems: 1
          type: array
          description: List of animals
          items:
            $ref: '#/components/schemas/Animal'
      example:
        animals:
        - image:
            copyright: copyright
            url: url
          id: id
          title: title
          tasks:
          - roleId: roleId
            exercise: exercise
            audio: audio
          - roleId: roleId
            exercise: exercise
            audio: audio
        - image:
            copyright: copyright
            url: url
          id: id
          title: title
          tasks:
          - roleId: roleId
            exercise: exercise
            audio: audio
          - roleId: roleId
            exercise: exercise
            audio: audio
    Animal:
      required:
      - id
      - tasks
      - title
      type: object
      properties:
        id:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
          description: Animal identifier
        title:
          minLength: 1
          type: string
          description: Title of the animal
        image:
          $ref: '#/components/schemas/Image'
        tasks:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Task'
      example:
        image:
          copyright: copyright
          url: url
        id: id
        title: title
        tasks:
        - roleId: roleId
          exercise: exercise
          audio: audio
        - roleId: roleId
          exercise: exercise
          audio: audio
    AnimalWithTask:
      required:
      - id
      - task
      - title
      type: object
      properties:
        id:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
          description: Animal identifier
        title:
          minLength: 1
          type: string
          description: Title of the animal
        image:
          $ref: '#/components/schemas/Image'
        task:
          $ref: '#/components/schemas/Task'
      example:
        image:
          copyright: copyright
          url: url
        task:
          roleId: roleId
          exercise: exercise
          audio: audio
        id: id
        title: title
    Task:
      required:
      - exercise
      - roleId
      type: object
      properties:
        roleId:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
          description: Task related role identifier
        exercise:
          minLength: 1
          type: string
          description: Human readable description of an exercise which should be performed
        audio:
          type: string
          description: Url to an audio file which explains the exercise acoustically.
      example:
        roleId: roleId
        exercise: exercise
        audio: audio
    ParksResponse:
      type: object
      properties:
        parks:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Park'
      example:
        parks:
        - description: description
          id: id
          title: title
          numberOfQrCodes: 0
        - description: description
          id: id
          title: title
          numberOfQrCodes: 0
    Park:
      required:
      - id
      - title
      type: object
      properties:
        id:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
          description: Park identifier
        title:
          minLength: 1
          type: string
          description: The name/title of the park
        description:
          type: string
          description: Human readable description of the park
        numberOfQrCodes:
          minimum: 0
          type: integer
          description: Number of QR-Codes the park contains
          format: int32
      example:
        description: description
        id: id
        title: title
        numberOfQrCodes: 0
    RoleResponse:
      type: object
      properties:
        roles:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Role'
      example:
        roles:
        - description: description
          id: id
          title: title
        - description: description
          id: id
          title: title
    Role:
      required:
      - id
      - title
      type: object
      properties:
        id:
          minLength: 1
          pattern: "^[a-zA-Z0-9_-]{1,30}$"
          type: string
          description: Role identifier
        title:
          minLength: 1
          type: string
          description: The name/title of the role
        description:
          type: string
          description: Short description of the character
      example:
        description: description
        id: id
        title: title
  parameters:
    language:
      name: Accept-Language
      in: header
      description: "The desired language for response content.\n[RFC 2616](https://tools.ietf.org/html/rfc2616#page-104)\n"
      required: false
      style: simple
      explode: false
      schema:
        type: string

